apiVersion: apps/v1
kind: Deployment
metadata:
  name: will42-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: playground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
