apiVersion: v1
kind: Service
metadata:
  name: playground-service 
spec:
  selector:
    app: playground
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 8888
      nodePort: 30000
  type: NodePort